package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"backend_server/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (ArticleMedia)
// DB Table: Plural (article_media)
// Resource: Plural (ArticleMedia)
// Path: Plural (/article_media)
// View Template Folder: Plural (/templates/article_media/)

// ArticleMediaResource is the resource for the ArticleMedia model
type ArticleMediaResource struct {
	buffalo.Resource
}

// List gets all ArticleMedia. This function is mapped to the path
// GET /article_media
func (v ArticleMediaResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	articleMedia := &models.ArticleMedia{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all ArticleMedia from the DB
	if err := q.All(articleMedia); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("articleMedia", articleMedia)
		return c.Render(http.StatusOK, r.HTML("article_media/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(articleMedia))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(articleMedia))
	}).Respond(c)
}

// Show gets the data for one ArticleMedia. This function is mapped to
// the path GET /article_media/{article_media_id}
func (v ArticleMediaResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty ArticleMedia
	articleMedia := &models.ArticleMedia{}

	// To find the ArticleMedia the parameter article_media_id is used.
	if err := tx.Find(articleMedia, c.Param("article_media_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("articleMedia", articleMedia)

		return c.Render(http.StatusOK, r.HTML("article_media/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(articleMedia))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(articleMedia))
	}).Respond(c)
}

// Create adds a ArticleMedia to the DB. This function is mapped to the
// path POST /article_media
func (v ArticleMediaResource) Create(c buffalo.Context) error {
	// Allocate an empty ArticleMedia
	articleMedia := &models.ArticleMedia{}

	// Bind articleMedia to the html form elements
	if err := c.Bind(articleMedia); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(articleMedia)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("articleMedia", articleMedia)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("article_media/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "articleMedia.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/article_media/%v", articleMedia.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(articleMedia))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(articleMedia))
	}).Respond(c)
}

// Update changes a ArticleMedia in the DB. This function is mapped to
// the path PUT /article_media/{article_media_id}
func (v ArticleMediaResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty ArticleMedia
	articleMedia := &models.ArticleMedia{}

	if err := tx.Find(articleMedia, c.Param("article_media_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind ArticleMedia to the html form elements
	if err := c.Bind(articleMedia); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(articleMedia)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("articleMedia", articleMedia)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("article_media/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "articleMedia.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/article_media/%v", articleMedia.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(articleMedia))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(articleMedia))
	}).Respond(c)
}

// Destroy deletes a ArticleMedia from the DB. This function is mapped
// to the path DELETE /article_media/{article_media_id}
func (v ArticleMediaResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty ArticleMedia
	articleMedia := &models.ArticleMedia{}

	// To find the ArticleMedia the parameter article_media_id is used.
	if err := tx.Find(articleMedia, c.Param("article_media_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(articleMedia); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "articleMedia.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/article_media")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(articleMedia))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(articleMedia))
	}).Respond(c)
}
