package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"backend_server/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (ArticleCategory)
// DB Table: Plural (article_categories)
// Resource: Plural (ArticleCategories)
// Path: Plural (/article_categories)
// View Template Folder: Plural (/templates/article_categories/)

// ArticleCategoriesResource is the resource for the ArticleCategory model
type ArticleCategoriesResource struct {
	buffalo.Resource
}

// List gets all ArticleCategories. This function is mapped to the path
// GET /article_categories
func (v ArticleCategoriesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	articleCategories := &models.ArticleCategories{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all ArticleCategories from the DB
	if err := q.All(articleCategories); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("articleCategories", articleCategories)
		return c.Render(http.StatusOK, r.HTML("article_categories/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(articleCategories))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(articleCategories))
	}).Respond(c)
}

// Show gets the data for one ArticleCategory. This function is mapped to
// the path GET /article_categories/{article_category_id}
func (v ArticleCategoriesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty ArticleCategory
	articleCategory := &models.ArticleCategory{}

	// To find the ArticleCategory the parameter article_category_id is used.
	if err := tx.Find(articleCategory, c.Param("article_category_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("articleCategory", articleCategory)

		return c.Render(http.StatusOK, r.HTML("article_categories/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(articleCategory))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(articleCategory))
	}).Respond(c)
}

// Create adds a ArticleCategory to the DB. This function is mapped to the
// path POST /article_categories
func (v ArticleCategoriesResource) Create(c buffalo.Context) error {
	// Allocate an empty ArticleCategory
	articleCategory := &models.ArticleCategory{}

	// Bind articleCategory to the html form elements
	if err := c.Bind(articleCategory); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(articleCategory)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("articleCategory", articleCategory)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("article_categories/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "articleCategory.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/article_categories/%v", articleCategory.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(articleCategory))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(articleCategory))
	}).Respond(c)
}

// Update changes a ArticleCategory in the DB. This function is mapped to
// the path PUT /article_categories/{article_category_id}
func (v ArticleCategoriesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty ArticleCategory
	articleCategory := &models.ArticleCategory{}

	if err := tx.Find(articleCategory, c.Param("article_category_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind ArticleCategory to the html form elements
	if err := c.Bind(articleCategory); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(articleCategory)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("articleCategory", articleCategory)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("article_categories/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "articleCategory.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/article_categories/%v", articleCategory.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(articleCategory))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(articleCategory))
	}).Respond(c)
}

// Destroy deletes a ArticleCategory from the DB. This function is mapped
// to the path DELETE /article_categories/{article_category_id}
func (v ArticleCategoriesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty ArticleCategory
	articleCategory := &models.ArticleCategory{}

	// To find the ArticleCategory the parameter article_category_id is used.
	if err := tx.Find(articleCategory, c.Param("article_category_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(articleCategory); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "articleCategory.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/article_categories")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(articleCategory))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(articleCategory))
	}).Respond(c)
}
