package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"backend_server/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (MediaCategory)
// DB Table: Plural (media_categories)
// Resource: Plural (MediaCategories)
// Path: Plural (/media_categories)
// View Template Folder: Plural (/templates/media_categories/)

// MediaCategoriesResource is the resource for the MediaCategory model
type MediaCategoriesResource struct {
	buffalo.Resource
}

// List gets all MediaCategories. This function is mapped to the path
// GET /media_categories
func (v MediaCategoriesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	mediaCategories := &models.MediaCategories{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all MediaCategories from the DB
	if err := q.All(mediaCategories); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("mediaCategories", mediaCategories)
		return c.Render(http.StatusOK, r.HTML("media_categories/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(mediaCategories))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(mediaCategories))
	}).Respond(c)
}

// Show gets the data for one MediaCategory. This function is mapped to
// the path GET /media_categories/{media_category_id}
func (v MediaCategoriesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty MediaCategory
	mediaCategory := &models.MediaCategory{}

	// To find the MediaCategory the parameter media_category_id is used.
	if err := tx.Find(mediaCategory, c.Param("media_category_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("mediaCategory", mediaCategory)

		return c.Render(http.StatusOK, r.HTML("media_categories/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(mediaCategory))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(mediaCategory))
	}).Respond(c)
}

// Create adds a MediaCategory to the DB. This function is mapped to the
// path POST /media_categories
func (v MediaCategoriesResource) Create(c buffalo.Context) error {
	// Allocate an empty MediaCategory
	mediaCategory := &models.MediaCategory{}

	// Bind mediaCategory to the html form elements
	if err := c.Bind(mediaCategory); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(mediaCategory)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("mediaCategory", mediaCategory)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("media_categories/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "mediaCategory.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/media_categories/%v", mediaCategory.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(mediaCategory))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(mediaCategory))
	}).Respond(c)
}

// Update changes a MediaCategory in the DB. This function is mapped to
// the path PUT /media_categories/{media_category_id}
func (v MediaCategoriesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty MediaCategory
	mediaCategory := &models.MediaCategory{}

	if err := tx.Find(mediaCategory, c.Param("media_category_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind MediaCategory to the html form elements
	if err := c.Bind(mediaCategory); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(mediaCategory)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("mediaCategory", mediaCategory)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("media_categories/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "mediaCategory.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/media_categories/%v", mediaCategory.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(mediaCategory))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(mediaCategory))
	}).Respond(c)
}

// Destroy deletes a MediaCategory from the DB. This function is mapped
// to the path DELETE /media_categories/{media_category_id}
func (v MediaCategoriesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty MediaCategory
	mediaCategory := &models.MediaCategory{}

	// To find the MediaCategory the parameter media_category_id is used.
	if err := tx.Find(mediaCategory, c.Param("media_category_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(mediaCategory); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "mediaCategory.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/media_categories")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(mediaCategory))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(mediaCategory))
	}).Respond(c)
}
