package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"backend_server/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Status)
// DB Table: Plural (statuses)
// Resource: Plural (Statuses)
// Path: Plural (/statuses)
// View Template Folder: Plural (/templates/statuses/)

// StatusesResource is the resource for the Status model
type StatusesResource struct {
	buffalo.Resource
}

// List gets all Statuses. This function is mapped to the path
// GET /statuses
func (v StatusesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	statuses := &models.Statuses{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Statuses from the DB
	if err := q.All(statuses); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("statuses", statuses)
		return c.Render(http.StatusOK, r.HTML("statuses/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(statuses))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(statuses))
	}).Respond(c)
}

// Show gets the data for one Status. This function is mapped to
// the path GET /statuses/{status_id}
func (v StatusesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Status
	status := &models.Status{}

	// To find the Status the parameter status_id is used.
	if err := tx.Find(status, c.Param("status_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("status", status)

		return c.Render(http.StatusOK, r.HTML("statuses/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(status))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(status))
	}).Respond(c)
}

// Create adds a Status to the DB. This function is mapped to the
// path POST /statuses
func (v StatusesResource) Create(c buffalo.Context) error {
	// Allocate an empty Status
	status := &models.Status{}

	// Bind status to the html form elements
	if err := c.Bind(status); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(status)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("status", status)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("statuses/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "status.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/statuses/%v", status.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(status))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(status))
	}).Respond(c)
}

// Update changes a Status in the DB. This function is mapped to
// the path PUT /statuses/{status_id}
func (v StatusesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Status
	status := &models.Status{}

	if err := tx.Find(status, c.Param("status_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Status to the html form elements
	if err := c.Bind(status); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(status)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("status", status)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("statuses/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "status.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/statuses/%v", status.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(status))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(status))
	}).Respond(c)
}

// Destroy deletes a Status from the DB. This function is mapped
// to the path DELETE /statuses/{status_id}
func (v StatusesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Status
	status := &models.Status{}

	// To find the Status the parameter status_id is used.
	if err := tx.Find(status, c.Param("status_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(status); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "status.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/statuses")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(status))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(status))
	}).Respond(c)
}
